id: P963F53BF
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS22941
  title: རྫོགས་པ་ཆེན་པོ་སེམས་ཉིད་ངལ་གསོའི་འགྲེལ་པ།
  volumes:
    50fca12da0904769b1158ce4c09d30df:
      image_group_id: I8LS22943
      title: ''
      base_file: v001.txt
  author: ''
